### ISSUE TITLE
smart-light build issue

### ISSUE THREAD

**Issue by vlast01** [apple/swift-matter-examples#30]
hello. I'm facing an issue when trying to build smart-light project. led-blink and template proj work fine. 

I would be appreciated for any ideas or hints. 

[logs.txt](https://github.com/user-attachments/files/17874187/logs.txt)

**Comment by kubamracek** [comment]
Resolved via https://github.com/apple/swift-matter-examples/pull/32

(Actually the concrete fix for the compiler crash was fixed on the toolchain side, and the newest toolchain now builds fine.)
